apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: ${APP_NAME}
  type: NodePort